// dropdown.js

// Export your dropdown options
export const note4Options =  [
    "F00.0 Dementia in Alzheimer's disease with early onset",
    "F00.00 Dementia in Alzheimer's disease with early onset Without additional symptoms",
    "F00.01 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly delusional",
    "F00.02 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly hallucinatory",
    "F00.03 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly depressive",
    "F00.04 Dementia in Alzheimer's disease with early onset with Other mixed symptoms",
    "F00.1 Dementia in Alzheimer's disease with late onset",
    "F00.10 Dementia in Alzheimer's disease with late onset Without additional symptoms",
    "F00.11 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly delusional",
    "F00.12 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly hallucinatory",
    "F00.13 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly depressive",
    "F00.14 Dementia in Alzheimer's disease with late onset with Other mixed symptoms",
    "F00.2 Dementia in Alzheimer's disease, atypical or mixed type",
    "F00.9 Dementia in Alzheimer's disease, unspecified",
    "F01 Vascular dementia",
    "F01.0 Vascular dementia of acute onset",
    "F01.00 Vascular dementia of acute onset Without additional symptoms",
    "F01.01 Vascular dementia of acute onset With Other symptoms, predominantly delusional",
    "F01.02 Vascular dementia of acute onset With Other symptoms, predominantly hallucinatory",
    "F01.03 Vascular dementia of acute onset With Other symptoms, predominantly depressive",
    "F01.04 Vascular dementia of acute onset With Other mixed symptoms",
    "F01.1 Multi-infarct dementia",
    "F01.2 Subcortical vascular dementia",
    "F01.3 Mixed cortical and subcortical vascular dementia",
    "F01.8 Other vascular dementia",
    "FO1.9 Vascular dementia, unspecified",
    "F02 Dementia in other diseases classified elsewhere",
    "F02.0 Dementia in Pick's disease",
    "F02.1 Dementia in Creutzfeldt - Jakob disease",
    "F02.2 Dementia in Huntington's disease",
    "F02.3 Dementia in Parkinson's disease",
    "F02.4 Dementia in human immunodeficiency virus [HIV] disease",
    "F02.8 Dementia in other specified diseases classified elsewhere",
    "F03 Unspecified dementia",
    "F04 Organic amnesic syndrome, not induced by alcohol and other psychoactive substances",
    "F05 Delirium, not induced by alcohol and other psychoactive substances",
    "F05.0 Delirium, not superimposed on dementia, so described",
    "F05.1 Delirium, superimposed on dementia",
    "F05.8 Other delirium",
    "F05.9 Delirium, unspecified",
    "F06 Other mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.0 Organic hallucinosis",
    "F06.1 Organic catatonic disorder",
    "F06.2 Organic delusional [schizophrenia-like] disorder",
    "F06.3 Organic mood [affective] disorders",
    "F06.30 Organic manic disorder",
    "F06.31 Organic bipolar affective disorder",
    "F06.32 Organic depressive disorder",
    "F06.33 Organic mixed affective disorder",
    "F06.4 Organic anxiety disorder",
    "F06.5 Organic dissociative disorder",
    "F06.6 Organic emotionally labile [asthenic] disorder",
    "F06.7 Mild cognitive disorder",
    "F06.8 Other specified mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.9 Unspecified mental disorder due to brain damage and dysfunction and to physical disease",
    "F07 Personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.0 Organic personality disorder",
    "F07.1 Post encephalitic syndrome",
    "F07.2 Postconcussional syndrome",
    "F07.8 Other organic personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.9 Unspecified organic personality and behavioral disorder due to brain disease, damage and dysfunction",
    "F09 Unspecified organic or symptomatic mental disorder"
        "F10. Mental and behavioral disorders due to use of alcohol",
        "F10.0 Mental and behavioral disorders due to use of alcohol Acute intoxication",
        "F10.00 Mental and behavioral disorders due to use of alcohol Uncomplicated",
        "F10.01 Mental and behavioral disorders due to use of alcohol with trauma or other bodily injury",
        "F10.02 Mental and behavioral disorders due to use of alcohol with other medical complications",
        "F10.03 Mental and behavioral disorders due to use of alcohol with delirium",
        "F10.04 Mental and behavioral disorders due to use of alcohol with perceptual distortions",
        "F10.05 Mental and behavioral disorders due to use of alcohol with coma",
        "F10.06 Mental and behavioral disorders due to use of alcohol with convulsions",
        "F10.07 Mental and behavioral disorders due to use of alcohol Pathological intoxication",
        "F10.1 Mental and behavioral disorders due to use of alcohol, Harmful use",
        "F10.2 Mental and behavioral disorders due to use of alcohol, Dependence syndrome",
        "F10.3 Mental and behavioral disorders due to use of alcohol, withdrawal state",
        "F10.31 Mental and behavioral disorders due to use of alcohol, withdrawal state with convulsions",
        "F10.4 Mental and behavioral disorders due to use of alcohol, withdrawal state with delirium",
        "F10.41 Mental and behavioral disorders due to use of alcohol, withdrawal state with delirium with convulsions",
        "F10.5 Mental and behavioral disorders due to use of alcohol, Psychotic disorders",
        "F10.6 Mental and behavioral disorders due to use of alcohol, Amnesic syndrome",
        "F10.7 Mental and behavioral disorders due to use of alcohol, Residual disorders and late onset psychotic disorder",
        "F11. Mental and behavioral disorders due to use of opioids",
        "F12. Mental and behavioral disorders due to use of cannabinoids",
        "F13. Mental and behavioral disorders due to use of sedatives or hypnotics",
        "F14. Mental and behavioral disorders due to use of cocaine",
        "F15. Mental and behavioral disorders due to use of other stimulants, including caffeine",
        "F15.0 Mental and behavioral disorders due to use of other stimulants, Acute intoxication",
        "F15.00 Mental and behavioral disorders due to use of other stimulants, Uncomplicated",
        "F15.01 Mental and behavioral disorders due to use of other stimulants, With trauma or other bodily injury",
        "F15.02 Mental and behavioral disorders due to use of other stimulants, With other medical complications",
        "F15.03 Mental and behavioral disorders due to use of other stimulants, With delirium",
        "F15.04 Mental and behavioral disorders due to use of other stimulants, With perceptual distortions",
        "F15.05 Mental and behavioral disorders due to use of other stimulants, With coma",
        "F15.06 Mental and behavioral disorders due to use of other stimulants, With convulsions",
        "F15.07 Mental and behavioral disorders due to use of other stimulants, Pathological intoxication",
        "F15.1 Mental and behavioral disorders due to use of other stimulants, Harmful use",
        "F15.2 Mental and behavioral disorders due to use of other stimulants, Dependence syndrome",
        "F15.3 Mental and behavioral disorders due to use of other stimulants, withdrawal state",
        "F15.31 Mental and behavioral disorders due to use of other stimulants, withdrawal state with convulsions",
        "F15.4 Mental and behavioral disorders due to use of other stimulants, withdrawal state with delirium",
        "F15.41 Mental and behavioral disorders due to use of other stimulants, withdrawal state with delirium with convulsions",
        "F15.5 Mental and behavioral disorders due to use of other stimulants, Psychotic disorders",
        "F15.6 Mental and behavioral disorders due to use of other stimulants, Amnesic syndrome",
        "F15.7 Mental and behavioral disorders due to use of other stimulants, Residual disorders and late onset psychotic disorder",
        "F16. Mental and behavioral disorders due to use of hallucinogens",
        "F16.0 Mental and behavioral disorders due to use of hallucinogens, Acute intoxication",
        "F16.00 Mental and behavioral disorders due to use of hallucinogens, Uncomplicated",
        "F16.01 Mental and behavioral disorders due to use of hallucinogens, With trauma or other bodily injury",
        "F16.02 Mental and behavioral disorders due to use of hallucinogens, With other medical complications",
        "F16.03 Mental and behavioral disorders due to use of hallucinogens, With delirium",
        "F16.04 Mental and behavioral disorders due to use of hallucinogens, With perceptual distortions",
        "F16.05 Mental and behavioral disorders due to use of hallucinogens, With coma",
        "F16.06 Mental and behavioral disorders due to use of hallucinogens, With convulsions",
        "F16.07 Pathological intoxication",
        "F17. Mental and behavioral disorders due to use of tobacco",
        "F18. Mental and behavioral disorders due to use of volatile solvents",
        "F19. Mental and behavioral disorders due to multiple drug use and use of other psychoactive substances"
      ]
      
];

