// dropdown.js

// Export your dropdown options
export const note4Options =  [
    "F00.0 Dementia in Alzheimer's disease with early onset",
    "F00.00 Dementia in Alzheimer's disease with early onset Without additional symptoms",
    "F00.01 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly delusional",
    "F00.02 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly hallucinatory",
    "F00.03 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly depressive",
    "F00.04 Dementia in Alzheimer's disease with early onset with Other mixed symptoms",
    "F00.1 Dementia in Alzheimer's disease with late onset",
    "F00.10 Dementia in Alzheimer's disease with late onset Without additional symptoms",
    "F00.11 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly delusional",
    "F00.12 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly hallucinatory",
    "F00.13 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly depressive",
    "F00.14 Dementia in Alzheimer's disease with late onset with Other mixed symptoms",
    "F00.2 Dementia in Alzheimer's disease, atypical or mixed type",
    "F00.9 Dementia in Alzheimer's disease, unspecified",
    "F01 Vascular dementia",
    "F01.0 Vascular dementia of acute onset",
    "F01.00 Vascular dementia of acute onset Without additional symptoms",
    "F01.01 Vascular dementia of acute onset With Other symptoms, predominantly delusional",
    "F01.02 Vascular dementia of acute onset With Other symptoms, predominantly hallucinatory",
    "F01.03 Vascular dementia of acute onset With Other symptoms, predominantly depressive",
    "F01.04 Vascular dementia of acute onset With Other mixed symptoms",
    "F01.1 Multi-infarct dementia",
    "F01.2 Subcortical vascular dementia",
    "F01.3 Mixed cortical and subcortical vascular dementia",
    "F01.8 Other vascular dementia",
    "F01.9 Vascular dementia, unspecified",
    "F02 Dementia in other diseases classified elsewhere",
    "F02.0 Dementia in Pick's disease",
    "F02.1 Dementia in Creutzfeldt-Jakob disease",
    "F02.2 Dementia in Huntington's disease",
    "F02.3 Dementia in Parkinson's disease",
    "F02.4 Dementia in human immunodeficiency virus [HIV] disease",
    "F02.8 Dementia in other specified diseases classified elsewhere",
    "F03 Unspecified dementia",
    "F04 Organic amnesic syndrome, not induced by alcohol and other psychoactive substances",
    "F05 Delirium, not induced by alcohol and other psychoactive substances",
    "F05.0 Delirium, not superimposed on dementia, so described",
    "F05.1 Delirium, superimposed on dementia",
    "F05.8 Other delirium",
    "F05.9 Delirium, unspecified",
    "F06 Other mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.0 Organic hallucinosis",
    "F06.1 Organic catatonic disorder",
    "F06.2 Organic delusional [schizophrenia-like] disorder",
    "F06.3 Organic mood [affective] disorders",
    "F06.30 Organic manic disorder",
    "F06.31 Organic bipolar affective disorder",
    "F06.32 Organic depressive disorder",
    "F06.33 Organic mixed affective disorder",
    "F06.4 Organic anxiety disorder",
    "F06.5 Organic dissociative disorder",
    "F06.6 Organic emotionally labile [asthenic] disorder",
    "F06.7 Mild cognitive disorder",
    "F06.8 Other specified mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.9 Unspecified mental disorder due to brain damage and dysfunction and to physical disease",
    "F07 Personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.0 Organic personality disorder",
    "F07.1 Post encephalitic syndrome",
    "F07.2 Postconcussional syndrome",
    "F07.8 Other organic personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.9 Unspecified organic personality and behavioral disorder due to brain disease, damage and dysfunction",
    "F09 Unspecified organic or symptomatic mental disorder"
  ]
  
      
