// dropdown.js

// Export your dropdown options
export const note4Options =  [
    "F00.0 Dementia in Alzheimer's disease with early onset",
    "F00.00 Dementia in Alzheimer's disease with early onset Without additional symptoms",
    "F00.01 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly delusional",
    "F00.02 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly hallucinatory",
    "F00.03 Dementia in Alzheimer's disease with early onset with Other symptoms, predominantly depressive",
    "F00.04 Dementia in Alzheimer's disease with early onset with Other mixed symptoms",
    "F00.1 Dementia in Alzheimer's disease with late onset",
    "F00.10 Dementia in Alzheimer's disease with late onset Without additional symptoms",
    "F00.11 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly delusional",
    "F00.12 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly hallucinatory",
    "F00.13 Dementia in Alzheimer's disease with late onset with Other symptoms, predominantly depressive",
    "F00.14 Dementia in Alzheimer's disease with late onset with Other mixed symptoms",
    "F00.2 Dementia in Alzheimer's disease, atypical or mixed type",
    "F00.9 Dementia in Alzheimer's disease, unspecified",
    "F01 Vascular dementia",
    "F01.0 Vascular dementia of acute onset",
    "F01.00 Vascular dementia of acute onset Without additional symptoms",
    "F01.01 Vascular dementia of acute onset With Other symptoms, predominantly delusional",
    "F01.02 Vascular dementia of acute onset With Other symptoms, predominantly hallucinatory",
    "F01.03 Vascular dementia of acute onset With Other symptoms, predominantly depressive",
    "F01.04 Vascular dementia of acute onset With Other mixed symptoms",
    "F01.1 Multi-infarct dementia",
    "F01.2 Subcortical vascular dementia",
    "F01.3 Mixed cortical and subcortical vascular dementia",
    "F01.8 Other vascular dementia",
    "F01.9 Vascular dementia, unspecified",
    "F02 Dementia in other diseases classified elsewhere",
    "F02.0 Dementia in Pick's disease",
    "F02.1 Dementia in Creutzfeldt-Jakob disease",
    "F02.2 Dementia in Huntington's disease",
    "F02.3 Dementia in Parkinson's disease",
    "F02.4 Dementia in human immunodeficiency virus [HIV] disease",
    "F02.8 Dementia in other specified diseases classified elsewhere",
    "F03 Unspecified dementia",
    "F04 Organic amnesic syndrome, not induced by alcohol and other psychoactive substances",
    "F05 Delirium, not induced by alcohol and other psychoactive substances",
    "F05.0 Delirium, not superimposed on dementia, so described",
    "F05.1 Delirium, superimposed on dementia",
    "F05.8 Other delirium",
    "F05.9 Delirium, unspecified",
    "F06 Other mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.0 Organic hallucinosis",
    "F06.1 Organic catatonic disorder",
    "F06.2 Organic delusional [schizophrenia-like] disorder",
    "F06.3 Organic mood [affective] disorders",
    "F06.30 Organic manic disorder",
    "F06.31 Organic bipolar affective disorder",
    "F06.32 Organic depressive disorder",
    "F06.33 Organic mixed affective disorder",
    "F06.4 Organic anxiety disorder",
    "F06.5 Organic dissociative disorder",
    "F06.6 Organic emotionally labile [asthenic] disorder",
    "F06.7 Mild cognitive disorder",
    "F06.8 Other specified mental disorders due to brain damage and dysfunction and to physical disease",
    "F06.9 Unspecified mental disorder due to brain damage and dysfunction and to physical disease",
    "F07 Personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.0 Organic personality disorder",
    "F07.1 Post encephalitic syndrome",
    "F07.2 Postconcussional syndrome",
    "F07.8 Other organic personality and behavioral disorders due to brain disease, damage and dysfunction",
    "F07.9 Unspecified organic personality and behavioral disorder due to brain disease, damage and dysfunction",
    "F09 Unspecified organic or symptomatic mental disorder",
    "F10. Mental and behavioral disorders due to use of alcohol",
    "F10.0 Mental and behavioral disorders due to use of alcohol Acute intoxication",
    "F10.00 Mental and behavioral disorders due to use of alcohol Uncomplicated",
    "F10.01 Mental and behavioral disorders due to use of alcohol with trauma or other bodily injury",
    "F10.02 Mental and behavioral disorders due to use of alcohol with other medical complications",
    "F10.03 Mental and behavioral disorders due to use of alcohol with delirium",
    "F10.04 Mental and behavioral disorders due to use of alcohol with perceptual distortions",
    "F10.05 Mental and behavioral disorders due to use of alcohol with coma",
    "F10.06 Mental and behavioral disorders due to use of alcohol with convulsions",
    "F10.07 Mental and behavioral disorders due to use of alcohol Pathological intoxication",
    "F10.1 Mental and behavioral disorders due to use of alcohol, Harmful use",
    "F10.2 Mental and behavioral disorders due to use of alcohol, Dependence syndrome",
    "F10.3 Mental and behavioral disorders due to use of alcohol, withdrawal state",
    "F10.31 Mental and behavioral disorders due to use of alcohol, withdrawal state with convulsions",
    "F10.4 Mental and behavioral disorders due to use of alcohol, withdrawal state with delirium",
    "F10.41 Mental and behavioral disorders due to use of alcohol, withdrawal state with delirium with convulsions",
    "F10.5 Mental and behavioral disorders due to use of alcohol, Psychotic disorders",
    "F10.6 Mental and behavioral disorders due to use of alcohol, Amnesic syndrome",
    "F10.7 Mental and behavioral disorders due to use of alcohol, Residual disorders and late onset psychotic disorder",
    "F11. Mental and behavioral disorders due to use of opioids",
    "F12. Mental and behavioral disorders due to use of cannabinoids",
    "F13. Mental and behavioral disorders due to use of sedatives or hypnotics",
    "F14. Mental and behavioral disorders due to use of cocaine",
    "F15. Mental and behavioral disorders due to use of other stimulants, including caffeine",
    "F15.0 Mental and behavioral disorders due to use of other stimulants, Acute intoxication",
    "F15.00 Mental and behavioral disorders due to use of other stimulants, Uncomplicated",
    "F15.01 Mental and behavioral disorders due to use of other stimulants, With trauma or other bodily injury",
    "F15.02 Mental and behavioral disorders due to use of other stimulants, With other medical complications",
    "F15.03 Mental and behavioral disorders due to use of other stimulants, With delirium",
    "F15.04 Mental and behavioral disorders due to use of other stimulants, With perceptual distortions",
    "F15.05 Mental and behavioral disorders due to use of other stimulants, With coma",
    "F15.06 Mental and behavioral disorders due to use of other stimulants, With convulsions",
    "F15.07 Mental and behavioral disorders due to use of other stimulants, Pathological intoxication",
    "F15.1 Mental and behavioral disorders due to use of other stimulants, Harmful use",
    "F15.2 Mental and behavioral disorders due to use of other stimulants, Dependence syndrome",
    "F15.3 Mental and behavioral disorders due to use of other stimulants, withdrawal state",
    "F15.31 Mental and behavioral disorders due to use of other stimulants, withdrawal state with convulsions",
    "F15.4 Mental and behavioral disorders due to use of other stimulants, withdrawal state with delirium",
    "F15.41 Mental and behavioral disorders due to use of other stimulants, withdrawal state with delirium with convulsions",
    "F15.5 Mental and behavioral disorders due to use of other stimulants, Psychotic disorders",
    "F15.7 Mental and behavioral disorders due to use of other stimulants, Residual disorders and late onset psychotic disorder",
    "F16. Mental and behavioral disorders due to use of hallucinogens",
    "F16.0 Mental and behavioral disorders due to use of hallucinogens, Acute intoxication",
    "F16.00 Mental and behavioral disorders due to use of hallucinogens, Uncomplicated",
    "F16.01 Mental and behavioral disorders due to use of hallucinogens, With trauma or other bodily injury",
    "F16.02 Mental and behavioral disorders due to use of hallucinogens, With other medical complications",
    "F16.03 Mental and behavioral disorders due to use of hallucinogens, With delirium",
    "F16.04 Mental and behavioral disorders due to use of hallucinogens, With perceptual distortions",
    "F16.05 Mental and behavioral disorders due to use of hallucinogens, With coma",
    "F16.06 Mental and behavioral disorders due to use of hallucinogens, With convulsions",
    "F16.07 Mental and behavioral disorders due to use of hallucinogens, Pathological intoxication",
    "F17. Mental and behavioral disorders due to use of tobacco",
    "F18. Mental and behavioral disorders due to use of volatile solvents",
    "F19. Mental and behavioral disorders due to multiple drug use and use of other psychoactive substances",
    "F20 Schizophrenia",
    "F20.0 Paranoid schizophrenia",
    "F20.1 Hebephrenic schizophrenia",
    "F20.2 Catatonic schizophrenia",
    "F20.3 Undifferentiated schizophrenia",
    "F20.4 Post-schizophrenic depression",
    "F20.5 Residual schizophrenia",
    "F20.6 Simple schizophrenia",
    "F20.8 Other schizophrenia",
    "F20.9 Schizophrenia, unspecified",
    "F21 Schizotypal disorder",
    "F22 Persistent delusional disorders",
    "F22.0 Delusional disorder",
    "F22.8 Other persistent delusional disorders",
    "F22.9 Persistent delusional disorder, unspecified",
    "F23 Acute and transient psychotic disorders",
    "F23.0 Acute polymorphic psychotic disorder without symptoms of schizophrenia",
    "F23.1 Acute polymorphic psychotic disorder with symptoms of schizophrenia",
    "F23.2 Acute schizophrenia-like psychotic disorder",
    "F23.3 Other acute predominantly delusional psychotic disorders",
    "F23.8 Other acute and transient psychotic disorders",
    "F23.9 Acute and transient psychotic disorders unspecified",
    "F24 Induced delusional disorder",
    "F25 Schizoaffective disorders",
    "F25.0 Schizoaffective disorder, manic type",
    "F25.1 Schizoaffective disorder, depressive type",
    "F25.2 Schizoaffective disorder, mixed type",
    "F25.8 Other schizoaffective disorders",
    "F25.9 Schizoaffective disorder, unspecified",
    "F28 Other nonorganic psychotic disorders",
    "F29 Unspecified nonorganic psychosis",
    "F30 Manic episode",
    "F30.0 Hypomania",
    "F30.1 Mania without psychotic symptoms",
    "F30.2 Mania with psychotic symptoms",
    "F30.8 Other manic episodes",
    "F30.9 Manic episode, unspecified",
    "F31 Bipolar affective disorder",
    "F31.0 Bipolar affective disorder, current episode hypomanic",
    "F31.1 Bipolar affective disorder, current episode manic without psychotic symptoms",
    "F31.2 Bipolar affective disorder, current episode manic with psychotic symptoms",
    "F31.3 Bipolar affective disorder, current episode mild or moderate depression",
    "F31.30 Bipolar affective disorder, current episode mild or moderate Depression, Without somatic syndrome",
    "F31.31 Bipolar affective disorder, current episode mild or moderate Depression, With somatic syndrome",
    "F31.4 Bipolar affective disorder, current episode severe depression without psychotic symptoms",
    "F31.5 Bipolar affective disorder, current episode severe depression with psychotic symptoms",
    "F31.6 Bipolar affective disorder, current episode mixed",
    "F31.7 Bipolar affective disorder, currently in remission",
    "F31.8 Other bipolar affective disorders",
    "F31.9 Bipolar affective disorder, unspecified",
    "F32 Depressive episode",
    "F32.0 Mild depressive episode",
    "F32.00 Mild depressive episode, Without somatic syndrome",
    "F32.01 Mild depressive episode, With somatic syndrome",
    "F32.1 Moderate depressive episode",
    "F32.10 Moderate depressive episode, Without somatic syndrome",
    "F32.11 Moderate depressive episode, With somatic syndrome",
    "F32.2 Severe depressive episode without psychotic symptoms",
    "F32.3 Severe depressive episode with psychotic symptoms",
    "F32.8 Other depressive episodes",
    "F32.9 Depressive episode, unspecified",
    "F33 Recurrent depressive disorder",
    "F33.0 Recurrent depressive disorder, current episode mild",
    "F33.00 Recurrent depressive disorder, current episode mild, Without somatic syndrome",
    "F33.01 Recurrent depressive disorder, current episode mild, With somatic syndrome",
    "F33.1 Recurrent depressive disorder, current episode moderate",
    "F33.10 Recurrent depressive disorder, current episode moderate, Without somatic syndrome",
    "F33.11 Recurrent depressive disorder, current episode moderate, With somatic syndrome",
    "F33.2 Recurrent depressive disorder, current episode severe without psychotic symptoms",
    "F33.3 Recurrent depressive disorder, current episode severe with psychotic symptoms",
    "F33.4 Recurrent depressive disorder, currently in remission",
    "F33.8 Other recurrent depressive disorders",
    "F33.9 Recurrent depressive disorder, unspecified",
    "F34 Persistent mood [affective] disorders",
    "F34.0 Cyclothymia",
    "F34.1 Dysthymia",
    "F34.8 Other persistent mood [affective] disorders",
    "F34.9 Persistent mood [affective] disorder, unspecified",
    "F38 Other mood [affective] disorders",
    "F38.0 Other single mood [affective] disorders",
    "F38.00 Mixed affective episode",
    "F38.1 Other recurrent mood [affective] disorders",
    "F38.10 Other recurrent mood [affective] disorders, Recurrent brief depressive disorder",
    "F38.8 Other specified mood [affective] disorders",
    "F39 Unspecified mood [affective] disorder"
  ];
  
      
